
public enum ErrorReason
{
    ERR_GENERIC,
    ERR_ACCOUNT_EMAIL_EXISTS,
    ERR_ACCOUNT_USERNAME_EXISTS,
    ERR_ACCOUNT_USERNAME_AND_EMAIL_EXISTS,
    ERR_CREDENTIALS_MISSING,
    ERR_ACCESS_TOKEN_EMPTY,
    ERR_ACCESS_TOKEN_INVALID,
    ERR_ACCESS_PERMISSION_DENIED,
    ERR_MODE_NOT_RECOGNIZED,
    ERR_MODE_EMPTY,
    ERR_LOGIN_UNSUCCESSFUL,
    ERR_ACCOUNT_NONEXISTANT,
    ERR_PARAMETERS_MISSING_OR_INVALID,
    ERR_USER_UNDERAGE
}
